#!/usr/bin/env bash
# Scans the img folder and writes js/sign-images-data.js with the list of
# image filenames (excluding logo.png). Run when you add or remove images:
#
#   ./scripts/build-sign-images.sh
#   or: bash scripts/build-sign-images.sh

set -e
cd "$(dirname "$0")/.."
IMG_DIR="img"
OUTPUT="js/sign-images-data.js"

# List image files, exclude logo.png, sort, build JSON array
list=""
while IFS= read -r name; do
  [ -z "$name" ] && continue
  [ -n "$list" ] && list="$list,"
  list="$list\"$name\""
done < <(ls -1 "$IMG_DIR" 2>/dev/null | grep -iE '\.(png|jpg|jpeg|gif|webp)$' | grep -v '^logo\.png$' | sort)

mkdir -p js
printf '// Auto-generated by scripts/build-sign-images.sh – do not edit\nwindow.SIGN_IMAGES = [%s];\n' "$list" > "$OUTPUT"
count=0
[ -n "$list" ] && count=$(echo "$list" | tr ',' '\n' | wc -l | tr -d ' ')
echo "Wrote $OUTPUT with $count image(s)"